version: "3"
services:
  dockermongovue:
    container_name: dockermongovue
    restart: always
    build: .
    ports:
      - "8080:8080"
  #   links:
  #     - mongovue
  # mongovue:
  #   image: mongo:4.0
  #   container_name: mongovue
  #   ports:
  #     - 27018:27017
  #   volumes:
  #     - ./data/mongo:/data/db
    # command: mongod --bind_ip=0.0.0.0
